export const goodsData = [
  { title: 'Вращающийся стул Токио', image: 'product-photo-1', link: '#', price: '24 000' },
  { title: 'Мягкое кресло Манн-Уитни', image: 'product-photo-2', link: '#', price: '20 000', saleProcent: '30', oldPrice: '18 000', productSale: 'product--sale' },
  { title: 'Кожаный диван Колумб', image: 'product-photo-3', link: '#', price: '125 000' },
  { title: 'Диван Рэдмен', image: 'product-photo-4', link: '#', price: '82 000' },
  { title: 'Прикроватный столик Пьер', image: 'product-photo-5', link: '#', price: '16 000' },
  { title: 'Стул Детройт', image: 'product-photo-6', link: '#', price: '12 000' },
  { title: 'Тканевый диван Альфред', image: 'product-photo-7', link: '#', price: '92 000' },
  { title: 'Обеденный комплект для кухни Модерн', image: 'product-photo-8', link: '#', price: '30 000', saleProcent: '40', oldPrice: '50 000', productSale: 'product--sale' },
  { title: 'Мягкое кресло Фред', image: 'product-photo-9', link: '#', price: '61 000' },
  { title: 'Медный светильник Конг', image: 'product-photo-10', link: '#', price: '10 000' },
  { title: 'Деревянный табурет Роган', image: 'product-photo-11', link: '#', price: '2 400', saleProcent: '20', oldPrice: '3 000', productSale: 'product--sale' },
  { title: 'Обеденный комплект для кухни Вууд', image: 'product-photo-12', link: '#', price: '115 000' },
  { title: 'Мягкое кресло Девил', image: 'product-photo-13', link: '#', price: '54 000' },
  { title: 'Журнальный столик Ален', image: 'product-photo-14', link: '#', price: '18 000' },
  { title: 'Обеденный комплект для кухни Денвер', image: 'product-photo-15', link: '#', price: '86 000' },
  { title: 'Мягкое кресло Барби', image: 'product-photo-16', link: '#', price: '32 000' },
  { title: 'Комплект для веранды Вест', image: 'product-photo-17', link: '#', price: '94 000' },
  { title: 'Кресло Олдмен', image: 'product-photo-18', link: '#', price: '62 000' },
  { title: 'Детское кресло Манго', image: 'product-photo-19', link: '#', price: '8 400', saleProcent: '30', oldPrice: '12 000', productSale: 'product--sale' },
  { title: 'Деревянный комод Винди', image: 'product-photo-20', link: '#', price: '36 000' },
]
